#*******************************************************************************
# Copyright (c) 2020-2021 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_fdt Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_fdt.c

BASENAME    := test_fdt
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)

CFLAGS      +=

include rules.mk
