#*******************************************************************************
# Copyright (c) 2008-2011,2014,2020 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Libc Makefile
#

TOPDIR       := ..
include common.mk

SRC         := \
               atexit.c          \
               ctypes.c          \
               generic.c         \
               getopt.c          \
               inet_pton.c       \
               mem.c             \
               printf.c          \
               standard.c        \
               string.c

BASENAME    := c
TARGETTYPE  := lib

include rules.mk
