#*******************************************************************************
# Copyright (c) 2016 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_rts Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_rts.c

BASENAME    := test_rts
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)
CFLAGS      += -pedantic

include rules.mk
