#*******************************************************************************
# Copyright (c) 2016 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_gui Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_gui.c

BASENAME    := test_gui
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)
CFLAGS      += -pedantic

include rules.mk
