#*******************************************************************************
# Copyright (c) 2008-2011 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Libfat Makefile
#

TOPDIR       := ..
include common.mk

SRC         := cache.c           \
               fatchain.c        \
               open.c            \
               searchdir.c

BASENAME    := fat
TARGETTYPE  := lib

include rules.mk
