#*******************************************************************************
# Copyright (c) 2013 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Libmd5 Makefile
#

TOPDIR       := ..
include common.mk

SRC         := md5.c 

BASENAME    := md5
TARGETTYPE  := lib

include rules.mk
