#*******************************************************************************
# Copyright (c) 2013 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Libmd5 Makefile
#

TOPDIR       := ..
include common.mk

SRC         := md5.c 

BASENAME    := md5
TARGETTYPE  := lib

include rules.mk
