#*******************************************************************************
# Copyright (c) 2020 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_libc Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_libc.c

BASENAME    := test_libc
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)

CFLAGS      +=

include rules.mk
