#*******************************************************************************
# Copyright (c) 2020 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_libc Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_libc.c

BASENAME    := test_libc
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)

CFLAGS      +=

include rules.mk
