#*******************************************************************************
# Copyright (c) 2008-2011 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# ifgpxe Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := ifgpxe.c

BASENAME    := ifgpxe
TARGETTYPE  := app
INC         := $(TOPDIR)/bios/com32
LIBS        := $(ENV_LIB) $(BOOTLIB)

include rules.mk
