#*******************************************************************************
# Copyright (c) 2022 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_malloc Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_malloc.c

BASENAME    := test_malloc
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)

CFLAGS      +=

include rules.mk
