#*******************************************************************************
# Copyright (c) 2022 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# test_malloc Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := test_malloc.c

BASENAME    := test_malloc
TARGETTYPE  := app
LIBS        := $(BOOTLIB) $(ENV_LIB)

CFLAGS      +=

include rules.mk
