#*******************************************************************************
# Copyright (c) 2008-2012 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Libcrc Makefile
#

TOPDIR       := ..
include common.mk

SRC         := crc.c

BASENAME    := crc
TARGETTYPE  := lib

include rules.mk
