#*******************************************************************************
# Copyright (c) 2008-2012 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Libcrc Makefile
#

TOPDIR       := ..
include common.mk

SRC         := crc.c

BASENAME    := crc
TARGETTYPE  := lib

include rules.mk
