#*******************************************************************************
# Copyright (c) 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Menu Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := menu.c

BASENAME    := menu
TARGETTYPE  := app
INC         := $(UEFIINC)
LIBS        := $(ENV_LIB) $(BOOTLIB)

include rules.mk
