#*******************************************************************************
# Copyright (c) 2008-2011 Broadcom. All Rights Reserved.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Isobounce Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := isobounce.c

BASENAME    := isobounce
TARGETTYPE  := app
INC         := $(UEFIINC)
LIBS        := $(ENV_LIB) $(BOOTLIB)

include rules.mk
