#*******************************************************************************
# Copyright (c) 2008-2011 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: GPL-2.0
#*******************************************************************************

#
# Isobounce Makefile
#

TOPDIR      := ../..
include common.mk

SRC         := isobounce.c

BASENAME    := isobounce
TARGETTYPE  := app
INC         := $(UEFIINC)
LIBS        := $(ENV_LIB) $(BOOTLIB)

include rules.mk
